from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "Checkpoint": ("modal_training_gym.common.checkpoint", "Checkpoint"),
    "CheckpointType": ("modal_training_gym.common.checkpoint", "CheckpointType"),
    "convert_megatron_checkpoint_to_hf": (
        "modal_training_gym.common.checkpoint",
        "convert_megatron_checkpoint_to_hf",
    ),
    "CustomDeployment": (
        "modal_training_gym.common.deployment",
        "CustomDeployment",
    ),
    "DeepSeek_V4_Flash_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "DeepSeek_V4_Flash_SglangRecipe",
    ),
    "DatasetConfig": ("modal_training_gym.common.dataset", "DatasetConfig"),
    "Endpoint": ("modal_training_gym.common.endpoint", "Endpoint"),
    "HarborDataset": ("modal_training_gym.common.dataset", "HarborDataset"),
    "MetricConfig": ("modal_training_gym.common.metrics", "MetricConfig"),
    "TrackioConfig": ("modal_training_gym.common.trackio", "TrackioConfig"),
    "EvalConfig": ("modal_training_gym.common.eval", "EvalConfig"),
    "EvalConfigDurable": ("modal_training_gym.common.eval", "EvalConfigDurable"),
    "EvalResult": ("modal_training_gym.common.eval", "EvalResult"),
    "EvalRowResult": ("modal_training_gym.common.eval", "EvalRowResult"),
    "GpuAllocationError": ("modal_training_gym.common.errors", "GpuAllocationError"),
    "AudioEvalRowResult": ("modal_training_gym.common.eval", "AudioEvalRowResult"),
    "ImageEvalRowResult": ("modal_training_gym.common.eval", "ImageEvalRowResult"),
    "Sample": ("modal_training_gym.common.sample", "Sample"),
    "RewardEvent": ("modal_training_gym.common.sample", "RewardEvent"),
    "extract_code": ("modal_training_gym.common.eval", "extract_code"),
    "HarborEval": ("modal_training_gym.common.eval", "HarborEval"),
    "Gemma4_26B_A4B": ("modal_training_gym.common.models", "Gemma4_26B_A4B"),
    "Gemma4_26B_A4B_Recipe": (
        "modal_training_gym.train_recipes.miles_recipe",
        "Gemma4_26B_A4B_Recipe",
    ),
    "GLM_4_7": ("modal_training_gym.common.models", "GLM_4_7"),
    "GLM_4_7_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "GLM_4_7_Recipe",
    ),
    "GLM_4_7_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "GLM_4_7_SglangRecipe",
    ),
    "HFModelConfiguration": (
        "modal_training_gym.common.models",
        "HFModelConfiguration",
    ),
    "HuggingFaceDataset": ("modal_training_gym.common.dataset", "HuggingFaceDataset"),
    "MultimodalDataset": ("modal_training_gym.common.dataset", "MultimodalDataset"),
    "OnlineRollout": ("modal_training_gym.common.dataset", "OnlineRollout"),
    "MetadataStore": ("modal_training_gym.utils.metadata", "MetadataStore"),
    "ModalCaptureError": (
        "modal_training_gym.common.modal_refs",
        "ModalCaptureError",
    ),
    "ModelArchitecture": ("modal_training_gym.common.models", "ModelArchitecture"),
    "ModelConfig": ("modal_training_gym.common.models", "ModelConfig"),
    "Inkling_Small": ("modal_training_gym.common.models", "Inkling_Small"),
    "Inkling_Small_Recipe": (
        "modal_training_gym.train_recipes.miles_recipe",
        "Inkling_Small_Recipe",
    ),
    "Inkling_Small_LoRA_Recipe": (
        "modal_training_gym.train_recipes.miles_recipe",
        "Inkling_Small_LoRA_Recipe",
    ),
    "Moonlight_16B_A3B_Instruct": (
        "modal_training_gym.common.models",
        "Moonlight_16B_A3B_Instruct",
    ),
    "Moonlight_16B_A3B_Recipe": (
        "modal_training_gym.train_recipes.miles_recipe",
        "Moonlight_16B_A3B_Recipe",
    ),
    "MilesRecipe": ("modal_training_gym.train_recipes.miles_recipe", "MilesRecipe"),
    "ParsedResponse": ("modal_training_gym.common.models", "ParsedResponse"),
    "Qwen3_0_6B": ("modal_training_gym.common.models", "Qwen3_0_6B"),
    "Qwen3_0_6B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_0_6B_Recipe",
    ),
    "Qwen3_0_6B_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "Qwen3_0_6B_SglangRecipe",
    ),
    "Qwen3_0_6B_VllmRecipe": (
        "modal_training_gym.deploy_recipes.vllm_recipe",
        "Qwen3_0_6B_VllmRecipe",
    ),
    "Qwen3_1_7B": ("modal_training_gym.common.models", "Qwen3_1_7B"),
    "Qwen3_1_7B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_1_7B_Recipe",
    ),
    "Qwen3_1_7B_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "Qwen3_1_7B_SglangRecipe",
    ),
    "Qwen3_1_7B_VllmRecipe": (
        "modal_training_gym.deploy_recipes.vllm_recipe",
        "Qwen3_1_7B_VllmRecipe",
    ),
    "Qwen3_4B": ("modal_training_gym.common.models", "Qwen3_4B"),
    "Qwen3_4B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_4B_Recipe",
    ),
    "Qwen3_4B_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "Qwen3_4B_SglangRecipe",
    ),
    "Qwen3_4B_VllmRecipe": (
        "modal_training_gym.deploy_recipes.vllm_recipe",
        "Qwen3_4B_VllmRecipe",
    ),
    "Qwen3_5_0_8B": ("modal_training_gym.common.models", "Qwen3_5_0_8B"),
    "Qwen3_5_0_8B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_5_0_8B_Recipe",
    ),
    "Qwen3_5_2B": ("modal_training_gym.common.models", "Qwen3_5_2B"),
    "Qwen3_5_2B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_5_2B_Recipe",
    ),
    "Qwen3_5_4B": ("modal_training_gym.common.models", "Qwen3_5_4B"),
    "Qwen3_5_4B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_5_4B_Recipe",
    ),
    "Qwen3_5_4B_Miles_Recipe": (
        "modal_training_gym.train_recipes.miles_recipe",
        "Qwen3_5_4B_Miles_Recipe",
    ),
    "Qwen3_5_9B": ("modal_training_gym.common.models", "Qwen3_5_9B"),
    "Qwen3_5_9B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_5_9B_Recipe",
    ),
    "Qwen3_8B": ("modal_training_gym.common.models", "Qwen3_8B"),
    "Qwen3_8B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_8B_Recipe",
    ),
    "Qwen3_8B_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "Qwen3_8B_SglangRecipe",
    ),
    "Qwen3_8B_VllmRecipe": (
        "modal_training_gym.deploy_recipes.vllm_recipe",
        "Qwen3_8B_VllmRecipe",
    ),
    "Qwen3_30B": ("modal_training_gym.common.models", "Qwen3_30B"),
    "Qwen3_30B_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "Qwen3_30B_SglangRecipe",
    ),
    "Qwen3_30B_VllmRecipe": (
        "modal_training_gym.deploy_recipes.vllm_recipe",
        "Qwen3_30B_VllmRecipe",
    ),
    "Qwen3_6_35B": ("modal_training_gym.common.models", "Qwen3_6_35B"),
    "Qwen3_6_35B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_6_35B_Recipe",
    ),
    "Qwen3_6_35B_SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "Qwen3_6_35B_SglangRecipe",
    ),
    "Qwen3_6_35B_VllmRecipe": (
        "modal_training_gym.deploy_recipes.vllm_recipe",
        "Qwen3_6_35B_VllmRecipe",
    ),
    "Qwen3_6_27B": ("modal_training_gym.common.models", "Qwen3_6_27B"),
    "Qwen3_6_27B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_6_27B_Recipe",
    ),
    "Qwen3_6_27B_Recipe_Agentic": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_6_27B_Recipe_Agentic",
    ),
    "Qwen3_8_27B": ("modal_training_gym.common.models", "Qwen3_8_27B"),
    "Qwen3_8_27B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_8_27B_Recipe",
    ),
    "Qwen3_VL_8B": ("modal_training_gym.common.models", "Qwen3_VL_8B"),
    "Qwen3_VL_8B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_VL_8B_Recipe",
    ),
    "Qwen3_ASR_1_7B": ("modal_training_gym.common.models", "Qwen3_ASR_1_7B"),
    "Qwen3_ASR_1_7B_Recipe": (
        "modal_training_gym.train_recipes.slime_recipe",
        "Qwen3_ASR_1_7B_Recipe",
    ),
    "score_in_sandbox": ("modal_training_gym.common.eval", "score_in_sandbox"),
    "SglangRecipe": (
        "modal_training_gym.deploy_recipes.sglang_recipe",
        "SglangRecipe",
    ),
    "SlimeRecipe": ("modal_training_gym.train_recipes.slime_recipe", "SlimeRecipe"),
    "ToolCall": ("modal_training_gym.common.models", "ToolCall"),
    "TrainConfig": ("modal_training_gym.common.train", "TrainConfig"),
    "TrainingGymConfigError": (
        "modal_training_gym.common.errors",
        "TrainingGymConfigError",
    ),
    "TrainingGymError": ("modal_training_gym.common.errors", "TrainingGymError"),
    "TrainingGroup": ("modal_training_gym.common.training_group", "TrainingGroup"),
    "TrainingRun": ("modal_training_gym.common.run", "TrainingRun"),
    "TrainResult": ("modal_training_gym.common.train_result", "TrainResult"),
    "VllmRecipe": ("modal_training_gym.deploy_recipes.vllm_recipe", "VllmRecipe"),
    "WandbConfig": ("modal_training_gym.common.wandb", "WandbConfig"),
}

__all__ = [
    "CustomDeployment",
    "Checkpoint",
    "CheckpointType",
    "convert_megatron_checkpoint_to_hf",
    "DatasetConfig",
    "DeepSeek_V4_Flash_SglangRecipe",
    "Endpoint",
    "Gemma4_26B_A4B",
    "Gemma4_26B_A4B_Recipe",
    "GLM_4_7",
    "GLM_4_7_Recipe",
    "GLM_4_7_SglangRecipe",
    "HarborDataset",
    "EvalConfig",
    "EvalConfigDurable",
    "EvalResult",
    "EvalRowResult",
    "GpuAllocationError",
    "AudioEvalRowResult",
    "ImageEvalRowResult",
    "Sample",
    "RewardEvent",
    "extract_code",
    "HarborEval",
    "HFModelConfiguration",
    "HuggingFaceDataset",
    "MultimodalDataset",
    "OnlineRollout",
    "MetadataStore",
    "MetricConfig",
    "ModalCaptureError",
    "ModelArchitecture",
    "ModelConfig",
    "Inkling_Small",
    "Inkling_Small_Recipe",
    "Inkling_Small_LoRA_Recipe",
    "Moonlight_16B_A3B_Instruct",
    "Moonlight_16B_A3B_Recipe",
    "MilesRecipe",
    "ParsedResponse",
    "Qwen3_0_6B",
    "Qwen3_0_6B_Recipe",
    "Qwen3_0_6B_SglangRecipe",
    "Qwen3_0_6B_VllmRecipe",
    "Qwen3_1_7B",
    "Qwen3_1_7B_Recipe",
    "Qwen3_1_7B_SglangRecipe",
    "Qwen3_1_7B_VllmRecipe",
    "Qwen3_4B",
    "Qwen3_4B_Recipe",
    "Qwen3_4B_SglangRecipe",
    "Qwen3_4B_VllmRecipe",
    "Qwen3_5_0_8B",
    "Qwen3_5_0_8B_Recipe",
    "Qwen3_5_2B",
    "Qwen3_5_2B_Recipe",
    "Qwen3_5_4B",
    "Qwen3_5_4B_Miles_Recipe",
    "Qwen3_5_4B_Recipe",
    "Qwen3_5_9B",
    "Qwen3_5_9B_Recipe",
    "Qwen3_8B",
    "Qwen3_8B_Recipe",
    "Qwen3_8B_SglangRecipe",
    "Qwen3_8B_VllmRecipe",
    "Qwen3_30B",
    "Qwen3_30B_SglangRecipe",
    "Qwen3_30B_VllmRecipe",
    "Qwen3_6_35B",
    "Qwen3_6_35B_Recipe",
    "Qwen3_6_35B_SglangRecipe",
    "Qwen3_6_35B_VllmRecipe",
    "Qwen3_6_27B",
    "Qwen3_6_27B_Recipe",
    "Qwen3_6_27B_Recipe_Agentic",
    "Qwen3_8_27B",
    "Qwen3_8_27B_Recipe",
    "Qwen3_ASR_1_7B",
    "Qwen3_ASR_1_7B_Recipe",
    "Qwen3_VL_8B",
    "Qwen3_VL_8B_Recipe",
    "score_in_sandbox",
    "SglangRecipe",
    "SlimeRecipe",
    "ToolCall",
    "TrainConfig",
    "TrainingGymConfigError",
    "TrainingGymError",
    "TrainingGroup",
    "TrainingRun",
    "TrainResult",
    "TrackioConfig",
    "VllmRecipe",
    "WandbConfig",
]


def __getattr__(name: str):
    module_name, attr_name = _EXPORTS.get(name, (None, None))
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))
