"""TrainingGroup — expand one TrainConfig into validated sweep variants.

Example::

    group = TrainingGroup(
        base=TrainConfig(
            model=Qwen3_6_35B(),
            dataset=ds,
            recipe=Qwen3_6_35b_Recipe(num_rollout=10),
        ),
        grid={
            "recipe.lr": [1e-6, 5e-6, 1e-5],
            "recipe.rollout_temperature": [0.8, 1.0],
        },
        name="lr-temp-sweep",   # optional; becomes the group_id (autogenerated if omitted)
    )

    for overrides, cfg in group.iter_variants():
        print(overrides, cfg.recipe.lr)

    results = group.train(max_parallel=3)

``name`` becomes the dashboard group id; omit it for ``group-<hex>``.
"""

from __future__ import annotations

import copy
import dataclasses as _dc
import difflib
import re
import secrets
import traceback
from typing import Any

from modal_training_gym.common.run import TrainingRun
from modal_training_gym.common.train import TrainConfig
from modal_training_gym.common.train_result import TrainResult


class TrainingGroupError(ValueError):
    """Raised when a TrainingGroup grid references fields that don't exist."""


def _exception_summary(exc: BaseException, *, limit: int = 1000) -> str:
    message = str(exc).strip() or repr(exc).strip()
    name = type(exc).__name__
    if not message or message == f"{name}()":
        return name
    if message.startswith(f"{name}:") or message.startswith(f"{name}("):
        return message[:limit]
    return f"{name}: {message}"[:limit]


def _slugify(name: str) -> str:
    """Normalize a group name into a stable, id-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    if not slug:
        raise TrainingGroupError(
            f"group name {name!r} has no alphanumeric characters to form an id"
        )
    return slug


def _is_pydantic_model(obj: Any) -> bool:
    return hasattr(type(obj), "model_fields")


def _valid_fields(obj: Any) -> set[str]:
    """Public, settable field names on ``obj``."""
    if _dc.is_dataclass(obj):
        return {f.name for f in _dc.fields(obj) if not f.name.startswith("_")}

    names: set[str] = set()
    if _is_pydantic_model(obj):
        names |= set(type(obj).model_fields)
    for klass in type(obj).__mro__:
        names |= set(getattr(klass, "__annotations__", {}) or {})
    names |= set(vars(obj))
    return {n for n in names if not n.startswith("_")}


def _revalidate_recipe(recipe: Any) -> Any:
    """Rebuild a recipe from its fields to re-run pydantic validation."""
    if not _dc.is_dataclass(recipe):
        return recipe
    field_values = {
        f.name: getattr(recipe, f.name)
        for f in _dc.fields(recipe)
        if f.init is not False
    }
    return type(recipe)(**field_values)


class TrainingGroup:
    """A parameter sweep over a base ``TrainConfig``."""

    def __init__(
        self,
        base: TrainConfig,
        grid: dict[str, list[Any]] | None = None,
        *,
        name: str | None = None,
    ) -> None:
        self.base = base
        self.grid: dict[str, list[Any]] = dict(grid or {})
        self.name = name
        self.group_id = _slugify(name) if name else f"group-{secrets.token_hex(6)}"

        self.results: list[TrainResult] = []
        self.launches: list[TrainingRun] = []
        self.failures: list[tuple[dict[str, Any], BaseException]] = []
        self._variants: list[tuple[dict[str, Any], TrainConfig]] | None = None

        self._validate_grid_shape()
        self._validate_paths()

    # ── Validation ──────────────────────────────────────────────────────────

    def _validate_grid_shape(self) -> None:
        for path, values in self.grid.items():
            if not isinstance(path, str) or not path:
                raise TrainingGroupError(
                    f"grid keys must be non-empty strings, got {path!r}"
                )
            if isinstance(values, (str, bytes)) or not hasattr(values, "__iter__"):
                raise TrainingGroupError(
                    f"grid['{path}'] must be a list of values to sweep, got {type(values).__name__}"
                )
            self.grid[path] = list(values)

    def _validate_paths(self) -> None:
        """Check every override path resolves to a real field on the base."""
        problems: list[str] = []
        for path in self.grid:
            segments = path.split(".")
            obj: Any = self.base
            for i, seg in enumerate(segments):
                valid = _valid_fields(obj)
                if seg not in valid:
                    prefix = ".".join(segments[: i + 1])
                    suggestion = difflib.get_close_matches(seg, valid, n=3)
                    hint = (
                        f" (did you mean: {', '.join(suggestion)})"
                        if suggestion
                        else ""
                    )
                    problems.append(
                        f"  - '{path}': '{prefix}' is not a field of "
                        f"{type(obj).__name__}{hint}.\n"
                        f"    valid fields: {', '.join(sorted(valid))}"
                    )
                    break
                if i < len(segments) - 1:
                    obj = getattr(obj, seg)
        if problems:
            raise TrainingGroupError(
                "TrainingGroup grid has invalid field paths:\n" + "\n".join(problems)
            )

    # ── Variant expansion ─────────────────────────────────────────────────────

    def iter_variants(self) -> list[tuple[dict[str, Any], TrainConfig]]:
        """Expand the sweep grid.

        Returns:
            Pairs of overrides and validated training configs.
        """
        if self._variants is not None:
            return list(self._variants)

        self._validate_paths()
        keys = list(self.grid)
        combos: list[tuple[Any, ...]]
        if keys and all(self.grid[k] for k in keys):
            import itertools

            combos = list(itertools.product(*(self.grid[k] for k in keys)))
        else:
            combos = [()]
        self._variants = [
            (dict(zip(keys, combo)), self._build_variant(dict(zip(keys, combo))))
            for combo in combos
        ]
        return list(self._variants)

    def get_train_configs(self) -> list[TrainConfig]:
        """Build validated configs for each sweep point.

        Returns:
            Validated training configs.
        """
        return [cfg for _, cfg in self.iter_variants()]

    def _print_variant_plan(
        self, variants: list[tuple[dict[str, Any], TrainConfig]]
    ) -> None:
        for overrides, cfg in variants:
            print(f"[TrainingGroup]   {overrides!r}")
            if context_plan_line := cfg.context_plan_line():
                print(f"[TrainingGroup]     {context_plan_line}")

    def _build_variant(self, overrides: dict[str, Any]) -> TrainConfig:
        cfg = copy.deepcopy(self.base)
        cfg.group_id = self.group_id
        cfg.group_overrides = dict(overrides)
        cfg.group_axes = list(self.grid)

        recipe_touched = False
        for path, value in overrides.items():
            segments = path.split(".")
            target: Any = cfg
            for seg in segments[:-1]:
                target = getattr(target, seg)
            setattr(target, segments[-1], value)
            if segments[0] == "recipe":
                recipe_touched = True

        if recipe_touched:
            try:
                cfg.recipe = _revalidate_recipe(cfg.recipe)
            except Exception as exc:  # noqa: BLE001 — re-raise with variant context
                raise TrainingGroupError(
                    f"invalid override for variant {overrides!r}: {exc}"
                ) from exc
        return cfg

    # ── Execution ─────────────────────────────────────────────────────────────

    def train(
        self,
        *,
        max_parallel: int = 1,
        continue_on_error: bool = True,
    ) -> list[TrainResult]:
        """Train every variant.

        Args:
            max_parallel:
                Maximum number of variants to run at once.
            continue_on_error:
                Continue after a variant fails.

        Returns:
            Successful training results.
        """
        variants = self.iter_variants()
        results: list[TrainResult] = []
        failures: list[tuple[dict[str, Any], BaseException]] = []

        def _record_failure(overrides: dict[str, Any], exc: BaseException) -> None:
            if not continue_on_error:
                raise exc
            failures.append((overrides, exc))
            print(
                f"[TrainingGroup] variant {overrides!r} failed: "
                f"{_exception_summary(exc)}"
            )

        def _run(overrides: dict[str, Any], cfg: TrainConfig) -> None:
            try:
                results.append(cfg.train(show_output=max_parallel <= 1))
            except BaseException as exc:  # noqa: BLE001 — recorded per-variant
                _record_failure(overrides, exc)

        print(
            f"[TrainingGroup] {self.group_id}: launching {len(variants)} variant(s)"
            + (f" (max_parallel={max_parallel})" if max_parallel > 1 else "")
        )
        self._print_variant_plan(variants)
        if max_parallel <= 1:
            for overrides, cfg in variants:
                _run(overrides, cfg)
        else:
            for i in range(0, len(variants), max_parallel):
                batch = variants[i : i + max_parallel]
                launched: list[tuple[dict[str, Any], TrainingRun]] = []
                for overrides, cfg in batch:
                    try:
                        launched.append(
                            (
                                overrides,
                                cfg.launch(show_output=False, prepare_inputs=True),
                            )
                        )
                    except BaseException as exc:  # noqa: BLE001
                        _record_failure(overrides, exc)
                for overrides, launch in launched:
                    try:
                        results.append(launch.result())
                    except BaseException as exc:  # noqa: BLE001
                        _record_failure(overrides, exc)

        self.results = results
        self.failures = failures
        print(
            f"[TrainingGroup] {self.group_id}: "
            f"{len(results)} succeeded, {len(failures)} failed"
        )
        return results

    def launch(
        self,
        *,
        continue_on_error: bool = True,
        prepare_inputs: bool = False,
    ) -> list[TrainingRun]:
        """Launch every variant as a detached Modal call.

        Args:
            continue_on_error:
                Continue after a variant fails to launch.
            prepare_inputs:
                Materialize model and dataset inputs before launching.

        Returns:
            Launched training runs.
        """
        variants = self.iter_variants()
        launches: list[TrainingRun] = []
        failures: list[tuple[dict[str, Any], BaseException]] = []

        print(f"[TrainingGroup] {self.group_id}: launching {len(variants)} variant(s)")
        self._print_variant_plan(variants)
        for overrides, cfg in variants:
            try:
                launch = cfg.launch(
                    show_output=False,
                    prepare_inputs=prepare_inputs,
                )
                launches.append(launch)
                print(
                    f"[TrainingGroup] launched {overrides!r}: "
                    f"{launch.training_run_id} ({launch.modal_app_id})"
                )
            except BaseException as exc:  # noqa: BLE001 — recorded per-variant
                if not continue_on_error:
                    raise
                failures.append((overrides, exc))
                print(
                    f"[TrainingGroup] variant {overrides!r} launch failed: "
                    f"{_exception_summary(exc)}"
                )
                traceback.print_exception(type(exc), exc, exc.__traceback__)

        self.launches = launches
        self.failures = failures
        print(
            f"[TrainingGroup] {self.group_id}: "
            f"{len(launches)} launched, {len(failures)} failed"
        )
        return launches
