"""TrainingGroup grid expansion, validation, and grouping."""

import pytest

from modal_training_gym import TrainConfig, TrainingGroup
from modal_training_gym.common.dataset import HuggingFaceDataset
from modal_training_gym.common.models import Qwen3_6_35B
from modal_training_gym.common.run import TrainingRun
from modal_training_gym.common.training_group import TrainingGroupError
from modal_training_gym.train_recipes.slime_recipe.qwen3_6_35b import Qwen3_6_35b_Recipe


def _base() -> TrainConfig:
    return TrainConfig(
        model=Qwen3_6_35B(),
        dataset=HuggingFaceDataset(
            hf_repo="openai/gsm8k",
            input_column="question",
            output_column="answer",
        ),
        recipe=Qwen3_6_35b_Recipe(num_rollout=10),
    )


def test_grid_expands_to_cross_product():
    group = TrainingGroup(
        base=_base(),
        grid={
            "recipe.lr": [1e-6, 5e-6, 1e-5],
            "recipe.rollout_temperature": [0.8, 1.0],
        },
    )
    configs = group.get_train_configs()
    assert len(configs) == 6

    seen = {(c.recipe.lr, c.recipe.rollout_temperature) for c in configs}
    assert seen == {
        (1e-6, 0.8),
        (1e-6, 1.0),
        (5e-6, 0.8),
        (5e-6, 1.0),
        (1e-5, 0.8),
        (1e-5, 1.0),
    }


def test_variants_are_independent_and_base_untouched():
    base = _base()
    group = TrainingGroup(base=base, grid={"recipe.lr": [2e-6, 9e-6]})
    configs = group.get_train_configs()

    assert configs[0].recipe.lr == 2e-6
    assert configs[1].recipe.lr == 9e-6
    assert base.recipe.lr == Qwen3_6_35b_Recipe().lr
    assert configs[0].recipe is not configs[1].recipe
    assert all(c.recipe.num_rollout == 10 for c in configs)


def test_each_variant_shares_group_id():
    group = TrainingGroup(base=_base(), grid={"recipe.lr": [1e-6, 5e-6]})
    configs = group.get_train_configs()
    assert len(configs) == 2
    assert all(c.group_id == group.group_id for c in configs)


def test_name_becomes_slugified_group_id():
    group = TrainingGroup(
        base=_base(), grid={"recipe.lr": [1e-6]}, name="LR Temp Sweep!"
    )
    assert group.group_id == "lr-temp-sweep"
    assert all(c.group_id == "lr-temp-sweep" for c in group.get_train_configs())


def test_autogenerated_group_id_when_no_name():
    group = TrainingGroup(base=_base(), grid={"recipe.lr": [1e-6]})
    assert group.group_id.startswith("group-")
    other = TrainingGroup(base=_base())
    assert group.group_id != other.group_id


def test_blank_name_is_rejected():
    with pytest.raises(TrainingGroupError):
        TrainingGroup(base=_base(), name="!!!")


def test_empty_grid_yields_single_variant():
    group = TrainingGroup(base=_base())
    configs = group.get_train_configs()
    assert len(configs) == 1
    assert configs[0].group_id == group.group_id


def test_empty_grid_axis_yields_single_blank_variant():
    group = TrainingGroup(base=_base(), grid={"recipe.lr": []}, name="Blank Sweep")
    variants = group.iter_variants()

    assert len(variants) == 1
    overrides, cfg = variants[0]
    assert overrides == {}
    assert cfg.group_id == "blank-sweep"
    assert cfg.group_overrides == {}
    assert cfg.group_axes == ["recipe.lr"]


def test_empty_group_variant_records_blank_group_tags():
    group = TrainingGroup(base=_base(), grid={"recipe.lr": []}, name="Blank Sweep")
    cfg = group.get_train_configs()[0]

    assert cfg._build_run_metadata() == {
        "group_id": "blank-sweep",
        "group_tags": {
            "group_id": "blank-sweep",
            "axes": ["recipe.lr"],
            "overrides": {},
            "tags": [],
        },
    }


def test_invalid_field_path_raises_at_construction():
    with pytest.raises(TrainingGroupError) as exc:
        TrainingGroup(base=_base(), grid={"recipe.learnign_rate": [1e-6]})
    msg = str(exc.value)
    assert "learnign_rate" in msg
    assert "lr" in msg  # "did you mean" suggestion surfaces the real field


def test_invalid_root_path_raises():
    with pytest.raises(TrainingGroupError):
        TrainingGroup(base=_base(), grid={"recipie.lr": [1e-6]})


def test_non_list_grid_value_raises():
    with pytest.raises(TrainingGroupError):
        TrainingGroup(base=_base(), grid={"recipe.lr": 1e-6})


def test_bad_value_type_caught_before_training():
    group = TrainingGroup(base=_base(), grid={"recipe.lr": ["not-a-number"]})
    with pytest.raises(TrainingGroupError):
        group.get_train_configs()


def test_train_result_persists_group_id():
    from modal_training_gym.common.framework import Framework
    from modal_training_gym.common.train_result import TrainResult

    result = TrainResult(
        app_name="run-x",
        framework=Framework.SLIME,
        training_run_id="run-x",
        group_id="group-abc123",
    )
    restored = TrainResult(**TrainResult._parse_model_config(result._to_dict()))
    assert restored.group_id == "group-abc123"


def test_training_run_resolves_train_result():
    from modal_training_gym.common.framework import Framework
    from modal_training_gym.common.train_result import TrainResult

    class FakeFunctionCall:
        def get(self, timeout=None):
            assert timeout == 123
            return TrainResult(
                app_name="run-x",
                framework=Framework.SLIME,
                training_run_id="run-x",
                group_id="group-abc123",
            )._to_dict()

    run = TrainingRun(
        training_run_id="run-x",
        modal_app_id="",
        modal_app_url="",
        framework=Framework.SLIME,
        config={},
        function_call_id="fc-123",
        metadata={"group_id": "group-abc123"},
    )
    run._function_call = FakeFunctionCall()

    # group_id is derived from metadata, not stored separately.
    assert run.group_id == "group-abc123"

    result = run.result(timeout=123, stop_app_on_success=False)
    assert result.training_run_id == "run-x"
    assert result.group_id == "group-abc123"


def test_iter_variants_pairs_overrides_with_configs():
    group = TrainingGroup(base=_base(), grid={"recipe.lr": [1e-6, 5e-6]})
    variants = group.iter_variants()
    assert [ov for ov, _ in variants] == [
        {"recipe.lr": 1e-6},
        {"recipe.lr": 5e-6},
    ]
    assert all(cfg.recipe.lr == ov["recipe.lr"] for ov, cfg in variants)


def test_variant_plan_prints_overrides(capsys):
    group = TrainingGroup(base=_base(), grid={"recipe.lr": [1e-6, 5e-6]})
    variants = group.iter_variants()

    group._print_variant_plan(variants)

    output = capsys.readouterr().out
    for overrides, cfg in variants:
        assert repr(overrides) in output
        context_plan_line = cfg.context_plan_line()
        assert context_plan_line is not None
        assert context_plan_line in output


def test_group_variants_record_tag_metadata():
    group = TrainingGroup(
        base=_base(),
        name="Batch Sweep",
        grid={
            "recipe.rollout_batch_size": [16],
            "recipe.lr": [1e-6],
        },
    )
    overrides, cfg = group.iter_variants()[0]

    assert overrides == {
        "recipe.rollout_batch_size": 16,
        "recipe.lr": 1e-6,
    }
    assert cfg.group_id == "batch-sweep"
    assert cfg.group_overrides == overrides
    assert cfg.group_axes == ["recipe.rollout_batch_size", "recipe.lr"]

    metadata = cfg._build_run_metadata()
    assert metadata == {
        "group_id": "batch-sweep",
        "group_tags": {
            "group_id": "batch-sweep",
            "axes": ["recipe.rollout_batch_size", "recipe.lr"],
            "overrides": {
                "recipe.rollout_batch_size": 16,
                "recipe.lr": 1e-6,
            },
            "tags": [
                {
                    "key": "recipe.rollout_batch_size",
                    "label": "rollout batch size",
                    "value": 16,
                },
                {"key": "recipe.lr", "label": "lr", "value": 1e-6},
            ],
        },
    }
