# Generated by generate_tutorial.py — do not edit directly.
# Source: tutorials/tutorial_generator/multinode/000_kimi_k25.py

# > **Multi-node workspace required:** This is a multi-node example. To run it,
# > your Modal workspace must have multi-node enabled. Contact
# > [support@modal.com](mailto:support@modal.com) to enable multi-node.
# # Multi-node Kimi K2.5 LoRA training
#
# This tutorial runs LoRA GRPO on
# [Kimi-K2.5](https://huggingface.co/moonshotai/Kimi-K2.5), a
# Mixture-of-Experts model from Moonshot AI, using
# [miles](https://github.com/volcengine/verl) across **16 nodes
# (128 H200 GPUs)**.
#
# The `Kimi_K2_5_LoRA_Recipe` preset configures INT4-quantized
# training weights with BF16 reference weights, colocated actor/critic,
# and DeepScaler math reward verification.
# To run the tutorial, run the following command:
# ```
# uv run tutorials/multinode/000_kimi_k25/000_kimi_k25.py
# ```
# ## Prerequisites
#
# This tutorial requires a Modal Secret named `huggingface-secret` containing your
# `HF_TOKEN`. Create one at [modal.com/secrets](https://modal.com/secrets) if you
# haven't already — the cell below fails fast with instructions otherwise.

import modal

from modal_training_gym import (
    HuggingFaceDataset,
    Kimi_K2_5,
    Kimi_K2_5_LoRA_Recipe,
    TrainConfig,
)

# ## Dataset
#
# We use [DAPO-Math-17k](https://huggingface.co/datasets/zhuzilin/dapo-math-17k),
# a collection of math competition problems with verifiable answers.
# The `deepscaler` reward model checks whether the model's response
# matches the reference answer.

class MathDataset(HuggingFaceDataset):
    hf_repo = "zhuzilin/dapo-math-17k"
    input_column = ""
    output_column = ""
    input_key = "prompt"
    label_key = "label"
    output_format = "jsonl"
    apply_chat_template = True
    always_prepare = True

# ## Launch training
#
# `TrainConfig.launch()` starts the Modal app **detached** and returns a
# `TrainingRun` handle as soon as training is spawned. Detached means the run
# survives this process: closing the notebook, dropping your connection, or
# hitting Ctrl-C leaves the 16 nodes training on Modal.
#
# The handle records the Modal app id and the `train` function-call id, so the
# run can be waited on — or cancelled — from anywhere later.

def build_training_config() -> TrainConfig:
    return TrainConfig(
        model=Kimi_K2_5(),
        dataset=MathDataset(n_rows=10),
        recipe=Kimi_K2_5_LoRA_Recipe(),
    )

import modal

tutorial_cli_app = modal.App()

def _main_impl() -> None:
    try:
        modal.Secret.from_name("huggingface-secret").hydrate()
    except modal.exception.NotFoundError as e:
        raise RuntimeError(
            "Missing Modal Secret 'huggingface-secret'. Create one at "
            "https://modal.com/secrets with an HF_TOKEN entry, then re-run."
        ) from e

    training_run = build_training_config()
    run = training_run.launch()

    print(f"Training run:  {run.training_run_id}")
    print(f"Modal app:     {run.modal_app_url}")
    print(f"Function call: {run.function_call_id}")

    # ## Reattach later
    #
    # A launched run is addressable by id from any process — the handle is
    # reconstructed from the persisted `function_call_id`, so you don't need to
    # keep this session open:
    #
    # ```python
    # from modal_training_gym import TrainingRun
    #
    # run = TrainingRun.from_id("<training_run_id>")
    # train_result = run.result()  # block for the TrainResult
    #
    # # Or stop it early:
    # run.function_call.cancel(terminate_containers=True)
    # ```
    # ## Wait for the result (optional)
    #
    # `run.result()` blocks until training finishes and returns the
    # `TrainResult`. Interrupting the wait does **not** stop the run: a launched
    # run always lives in a detached Modal app, so Ctrl-C here only stops
    # waiting. To actually stop training, cancel the call:
    # `run.function_call.cancel(terminate_containers=True)`.
    #
    # Skip this cell entirely if you just want to launch and walk away.

    train_result = run.result()
    print(f"Training complete: {train_result.training_run_id}")

@tutorial_cli_app.local_entrypoint()
def main() -> None:
    _main_impl()

if __name__ == "__main__":
    main()
