# Generated by generate_tutorial.py — do not edit directly.
# Source: tutorials/tutorial_generator/slime_gsm8k.py

# # Qwen3-4B GRPO on GSM8K with SLIME on Modal
#
# Trains Qwen3-4B with GRPO on the GSM8K math dataset using
# [SLIME](https://github.com/slimerl/slime) on Modal. 4 nodes × 8×H200,
# actor and rollout colocated.
#
# Invoke any function on the returned `app` via `modal run`, or
# interactively with `app.run()` + `.remote()`.

import modal

from modal_training_gym.common.dataset import DatasetConfig
from modal_training_gym.common.models import Qwen3_4B
from modal_training_gym.common.wandb import WandbConfig
from modal_training_gym.frameworks.slime import (
    ModalConfig,
    SlimeConfig,
)
from modal_training_gym.frameworks.slime.config import DATA_PATH

# ## Define the dataset
#
# Subclass `DatasetConfig` with the path + interpretation fields this
# experiment uses, and implement `prepare()` to materialize the data
# into the shared data volume.

class GSM8KDataset(DatasetConfig):
    input_key = "messages"
    label_key = "label"
    apply_chat_template = True
    rollout_shuffle = True
    rm_type = "math"

    def __init__(self, data_path):
        self._data_path = str(data_path)
        self.prompt_data = f"{self._data_path}/gsm8k/train.parquet"
        self.eval_prompt_data = ["gsm8k", f"{self._data_path}/gsm8k/test.parquet"]

    def prepare(self):
        from datasets import load_dataset

        ds = load_dataset("zhuzilin/gsm8k")
        ds["train"].to_parquet(f"{self._data_path}/gsm8k/train.parquet")
        ds["test"].to_parquet(f"{self._data_path}/gsm8k/test.parquet")

# ## Define the experiment
#
# Instantiate `SlimeConfig(...)` directly with your model/dataset/logging
# containers and SLIME flags. Every attribute except `environment`,
# `async_mode`, and `slime_model_script` is forwarded to SLIME
# automatically (`field_name` → `--field-name`).

base_model = Qwen3_4B()
my_training_run = SlimeConfig(
    model=base_model,
    dataset=GSM8KDataset(DATA_PATH),
    wandb=WandbConfig(project="slime-grpo", group="qwen3-4b-gsm8k"),
    ref_load=base_model.model_name,
    megatron_to_hf_mode="bridge",
    actor_num_nodes=4,
    actor_num_gpus_per_node=8,
    colocate=True,
    num_rollout=1,
    rollout_batch_size=8,
    rollout_max_response_len=8192,
    rollout_temperature=1.0,
    rollout_num_gpus_per_engine=1,
    sglang_mem_fraction_static=0.7,
    n_samples_per_prompt=2,
    global_batch_size=16,
    use_fault_tolerance=True,
    eval_interval=20,
    n_samples_per_eval_prompt=4,
    eval_max_response_len=16384,
    eval_top_p=1.0,
    tensor_model_parallel_size=1,
    sequence_parallel=False,
    use_dynamic_batch_size=True,
    max_tokens_per_gpu=9216,
    recompute_granularity="full",
    recompute_method="uniform",
    recompute_num_layers=1,
    attention_dropout=0.0,
    hidden_dropout=0.0,
    accumulate_allreduce_grads_in_fp32=True,
    attention_softmax_in_fp32=True,
    optimizer="adam",
    lr=1e-6,
    lr_decay_style="constant",
    weight_decay=0.1,
    adam_beta1=0.9,
    adam_beta2=0.98,
    advantage_estimator="grpo",
    eps_clip=0.2,
    eps_clip_high=0.28,
    use_kl_loss=True,
    kl_loss_coef=0.0,
    kl_loss_type="low_var_kl",
    entropy_coef=0.0,
    modal=ModalConfig(gpu="H200"),
)

# ## Build the Modal app

app = my_training_run.build_app()

# ## Run it

# From the CLI:
#
# ```bash
# uv run modal run tutorials/slime_gsm8k/slime_gsm8k.py::app.download_model
# uv run modal run tutorials/slime_gsm8k/slime_gsm8k.py::app.prepare_dataset
# uv run modal run tutorials/slime_gsm8k/slime_gsm8k.py::app.convert_checkpoint
# uv run modal run --detach tutorials/slime_gsm8k/slime_gsm8k.py::app.train
# ```
