# Generated by generate_tutorial.py — do not edit directly.
# Source: tutorials/tutorial_generator/intro/001_deploy_base_model.py

# # Deploy the base model
#
# This tutorial shows you how to deploy a base model on Modal to use for evaluation. Here, we will use Qwen3-4B as the base model, but
# you can use any other model that is supported by the training-gym, or configure your own.
# To run the tutorial, run the following command:
# ```
# uv run python tutorials/intro/001_deploy_base_model.py
# ```
# ## Prerequisites
#
# This tutorial requires a Modal Secret named `huggingface-secret` containing your
# `HF_TOKEN`. Create one at [modal.com/secrets](https://modal.com/secrets) if you
# haven't already — the cell below fails fast with instructions otherwise.

import modal

import re

from modal_training_gym import (
    DeploymentConfig,
    EvalConfig,
    EvalRowResult,
    HuggingFaceDataset,
    Qwen3_4B,
    SlimeRecipe,
)

# The `chat_template_kwargs` parameter allows us to pass in a dictionary of kwargs to the chat template.
# This is useful for passing in additional parameters to the chat template, such as the enable_thinking parameter.

import modal

tutorial_cli_app = modal.App()

def _main_impl() -> None:
    try:
        modal.Secret.from_name("huggingface-secret").hydrate()
    except modal.exception.NotFoundError as e:
        raise RuntimeError(
            "Missing Modal Secret 'huggingface-secret'. Create one at "
            "https://modal.com/secrets with an HF_TOKEN entry, then re-run."
        ) from e

    # ## Serve the base model
    #
    # To deploy the base model, we can use the `DeploymentConfig` class. This allows us to deploy the model on Modal and get a handle to the deployed model.

    base_model = Qwen3_4B()
    base_model_deployment = DeploymentConfig(
        model=base_model,
    ).serve()
    print(f"Base model deployed to {base_model_deployment.url}")

@tutorial_cli_app.local_entrypoint()
def main() -> None:
    _main_impl()

if __name__ == "__main__":
    main()
