# Generated by generate_tutorial.py — do not edit directly.
# Source: tutorials/tutorial_generator/intro/001_deploy_base_model.py

# # Deploy a base model
#
# Before training or evaluating, you need a running inference endpoint. In this tutorial you'll deploy Qwen3-4B to Modal using `DeploymentConfig` and send it a generation request. Any model in the training-gym catalog works — Qwen3-4B is just a convenient default.
# To run the tutorial, run the following command:
# ```
# uv run python tutorials/intro/001_deploy_base_model.py
# ```
# ## Prerequisites
#
# This tutorial requires a Modal Secret named `huggingface-secret` containing your
# `HF_TOKEN`. Create one at [modal.com/secrets](https://modal.com/secrets) if you
# haven't already — the cell below fails fast with instructions otherwise.

import modal

from modal_training_gym import (
    DeploymentConfig,
    Qwen3_4B,
)

# ## Disabling thinking mode
#
# Qwen3 defaults to "thinking" mode, where the model reasons internally before answering. Pass `enable_thinking=False` via `chat_template_kwargs` to get a direct response instead.

import modal

tutorial_cli_app = modal.App()

def _main_impl() -> None:
    try:
        modal.Secret.from_name("huggingface-secret").hydrate()
    except modal.exception.NotFoundError as e:
        raise RuntimeError(
            "Missing Modal Secret 'huggingface-secret'. Create one at "
            "https://modal.com/secrets with an HF_TOKEN entry, then re-run."
        ) from e

    # ## Serve the base model
    #
    # `DeploymentConfig.serve()` launches an SGLang inference server on Modal and returns a deployment handle you can call directly.

    base_model = Qwen3_4B()
    base_model_deployment = DeploymentConfig(
        model=base_model,
    ).serve()
    print(f"Base model deployed to {base_model_deployment.url}")

@tutorial_cli_app.local_entrypoint()
def main() -> None:
    _main_impl()

if __name__ == "__main__":
    main()
