API_REFERENCE_MANIFEST = [
    {
        "class_name": "ModelConfig",
        "module": "modal_training_gym.common.models.base",
        "group": "models",
        "class_type": "behavior",
        "sidebar_label": "ModelConfig",
    },
    {
        "class_name": "HFModelConfiguration",
        "module": "modal_training_gym.common.models.base",
        "group": "models",
        "class_type": "behavior",
        "sidebar_label": "HFModelConfiguration",
    },
    {
        "class_name": "ModelArchitecture",
        "module": "modal_training_gym.common.models.base",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "ModelArchitecture",
    },
    {
        "class_name": "ToolCall",
        "module": "modal_training_gym.common.models.base",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "ToolCall",
    },
    {
        "class_name": "Qwen3_0_6B",
        "module": "modal_training_gym.common.models.qwen3_0_6b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3-0.6B",
    },
    {
        "class_name": "Qwen3_1_7B",
        "module": "modal_training_gym.common.models.qwen3_1_7b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3-1.7B",
    },
    {
        "class_name": "Qwen3_4B",
        "module": "modal_training_gym.common.models.qwen3_4b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3-4B",
    },
    {
        "class_name": "Qwen3_8B",
        "module": "modal_training_gym.common.models.qwen3_8b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3-8B",
    },
    {
        "class_name": "Qwen3_5_0_8B",
        "module": "modal_training_gym.common.models.qwen3_5_0_8b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-0.8B",
    },
    {
        "class_name": "Qwen3_5_2B",
        "module": "modal_training_gym.common.models.qwen3_5_2b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-2B",
    },
    {
        "class_name": "Qwen3_5_4B",
        "module": "modal_training_gym.common.models.qwen3_5_4b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-4B",
    },
    {
        "class_name": "Qwen3_5_9B",
        "module": "modal_training_gym.common.models.qwen3_5_9b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-9B",
    },
    {
        "class_name": "Qwen3_30B",
        "module": "modal_training_gym.common.models.qwen3_30b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3-30B-A3B",
    },
    {
        "class_name": "Moonlight_16B_A3B_Instruct",
        "module": "modal_training_gym.common.models.moonlight_16b_a3b_instruct",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Moonlight-16B-A3B-Instruct",
    },
    {
        "class_name": "Gemma4_26B_A4B",
        "module": "modal_training_gym.common.models.gemma4_26b_a4b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Gemma-4-26B-A4B-it",
    },
    {
        "class_name": "Inkling_Small",
        "module": "modal_training_gym.common.models.inkling_small",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Inkling-Small",
    },
    {
        "class_name": "Nemotron3_Ultra_550B_A55B",
        "module": "modal_training_gym.common.models.nemotron3_ultra_550b_a55b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Nemotron-3-Ultra-550B-A55B",
    },
    {
        "class_name": "GLM_4_7",
        "module": "modal_training_gym.common.models.glm_4_7",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "GLM-4.7",
    },
    {
        "class_name": "Qwen3_6_35B",
        "module": "modal_training_gym.common.models.qwen3_6_35b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.6-35B-A3B",
    },
    {
        "class_name": "Qwen3_6_27B",
        "module": "modal_training_gym.common.models.qwen3_6_27b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.6-27B",
    },
    {
        "class_name": "Qwen3_8_27B",
        "module": "modal_training_gym.common.models.qwen3_8_27b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.8-27B",
    },
    {
        "class_name": "Qwen3_ASR_1_7B",
        "module": "modal_training_gym.common.models.qwen3_asr_1_7b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3-ASR-1.7B",
    },
    {
        "class_name": "Qwen3_VL_8B",
        "module": "modal_training_gym.common.models.qwen3_vl_8b",
        "group": "models",
        "class_type": "config_data",
        "sidebar_label": "Qwen3-VL-8B",
    },
    {
        "class_name": "DatasetConfig",
        "module": "modal_training_gym.common.dataset",
        "group": "datasets",
        "class_type": "config_data",
        "sidebar_label": "DatasetConfig",
    },
    {
        "class_name": "HuggingFaceDataset",
        "module": "modal_training_gym.common.dataset",
        "group": "datasets",
        "class_type": "config_data",
        "sidebar_label": "HuggingFaceDataset",
    },
    {
        "class_name": "HarborDataset",
        "module": "modal_training_gym.common.dataset",
        "group": "datasets",
        "class_type": "config_data",
        "sidebar_label": "HarborDataset",
    },
    {
        "class_name": "Qwen3_5_4B_Miles_Recipe",
        "module": "modal_training_gym.train_recipes.miles_recipe.qwen3_5_4b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_5_4B_Miles_Recipe",
    },
    {
        "class_name": "Moonlight_16B_A3B_Recipe",
        "module": "modal_training_gym.train_recipes.miles_recipe.moonlight_16b_a3b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Moonlight_16B_A3B_Recipe",
    },
    {
        "class_name": "Gemma4_26B_A4B_Recipe",
        "module": "modal_training_gym.train_recipes.miles_recipe.gemma4_26b_a4b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Gemma4_26B_A4B_Recipe",
    },
    {
        "class_name": "Inkling_Small_Recipe",
        "module": "modal_training_gym.train_recipes.miles_recipe.inkling",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Inkling_Small_Recipe",
    },
    {
        "class_name": "Inkling_Small_LoRA_Recipe",
        "module": "modal_training_gym.train_recipes.miles_recipe.inkling",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Inkling_Small_LoRA_Recipe",
    },
    {
        "class_name": "Nemotron3_Ultra_550B_A55B_Recipe",
        "module": "modal_training_gym.train_recipes.miles_recipe.nemotron3_ultra_550b_a55b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Nemotron3_Ultra_550B_A55B_Recipe",
    },
    {
        "class_name": "Qwen3_6_35B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_6_35b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_6_35B_Recipe",
    },
    {
        "class_name": "Qwen3_6_27B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_6_27b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_6_27B_Recipe",
    },
    {
        "class_name": "Qwen3_8_27B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_8_27b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_8_27B_Recipe",
    },
    {
        "class_name": "Qwen3_5_0_8B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_5_0_8b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-0.8B_Recipe",
    },
    {
        "class_name": "Qwen3_5_2B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_5_2b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-2B_Recipe",
    },
    {
        "class_name": "Qwen3_5_4B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_5_4b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-4B_Recipe",
    },
    {
        "class_name": "Qwen3_5_9B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_5_9b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3.5-9B_Recipe",
    },
    {
        "class_name": "Qwen3_0_6B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_0_6b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_0_6B_Recipe",
    },
    {
        "class_name": "Qwen3_1_7B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_1_7b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_1_7B_Recipe",
    },
    {
        "class_name": "Qwen3_4B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_4b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_4B_Recipe",
    },
    {
        "class_name": "Qwen3_8B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_8b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_8B_Recipe",
    },
    {
        "class_name": "GLM_4_7_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.glm_4_7",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "GLM_4_7_Recipe",
    },
    {
        "class_name": "Qwen3_ASR_1_7B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_asr_1_7b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_ASR_1_7B_Recipe",
    },
    {
        "class_name": "Qwen3_VL_8B_Recipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.qwen3_vl_8b",
        "group": "recipes",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_VL_8B_Recipe",
    },
    {
        "class_name": "TrainConfig",
        "module": "modal_training_gym.common.train",
        "group": "training",
        "class_type": "config_data",
        "sidebar_label": "TrainConfig",
    },
    {
        "class_name": "TrainingRun",
        "module": "modal_training_gym.common.run",
        "group": "training",
        "class_type": "behavior",
        "sidebar_label": "TrainingRun",
    },
    {
        "class_name": "TrainingGroup",
        "module": "modal_training_gym.common.training_group",
        "group": "training",
        "class_type": "behavior",
        "sidebar_label": "TrainingGroup",
    },
    {
        "class_name": "TrainResult",
        "module": "modal_training_gym.common.train_result",
        "group": "training",
        "class_type": "behavior",
        "sidebar_label": "TrainResult",
    },
    {
        "class_name": "MetricConfig",
        "module": "modal_training_gym.common.metrics",
        "group": "training",
        "class_type": "config_data",
        "sidebar_label": "MetricConfig",
    },
    {
        "class_name": "TrackioConfig",
        "module": "modal_training_gym.common.trackio",
        "group": "training",
        "class_type": "config_data",
        "sidebar_label": "TrackioConfig",
    },
    {
        "class_name": "WandbConfig",
        "module": "modal_training_gym.common.wandb",
        "group": "training",
        "class_type": "config_data",
        "sidebar_label": "WandbConfig",
    },
    {
        "class_name": "ModalRayCluster",
        "module": "modal_training_gym.common.ray_cluster",
        "group": "training",
        "class_type": "behavior",
        "sidebar_label": "ModalRayCluster",
    },
    {
        "class_name": "SlimeRecipe",
        "module": "modal_training_gym.train_recipes.slime_recipe.recipe",
        "group": "training",
        "class_type": "config_data",
        "sidebar_label": "SlimeRecipe",
    },
    {
        "class_name": "MilesRecipe",
        "module": "modal_training_gym.train_recipes.miles_recipe.recipe",
        "group": "training",
        "class_type": "config_data",
        "sidebar_label": "MilesRecipe",
    },
    {
        "class_name": "CustomDeployment",
        "module": "modal_training_gym.common.deployment",
        "group": "deployment",
        "class_type": "behavior",
        "sidebar_label": "CustomDeployment",
    },
    {
        "class_name": "Endpoint",
        "module": "modal_training_gym.common.endpoint",
        "group": "deployment",
        "class_type": "behavior",
        "sidebar_label": "Endpoint",
    },
    {
        "class_name": "ParsedResponse",
        "module": "modal_training_gym.common.models.base",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "ParsedResponse",
    },
    {
        "class_name": "SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "SglangRecipe",
    },
    {
        "class_name": "VllmRecipe",
        "module": "modal_training_gym.deploy_recipes.vllm_recipe",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "VllmRecipe",
    },
    {
        "class_name": "DeepSeek_V4_Flash_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.deepseek_v4_flash",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "DeepSeek_V4_Flash_SglangRecipe",
    },
    {
        "class_name": "GLM_4_7_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.glm_4_7",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "GLM_4_7_SglangRecipe",
    },
    {
        "class_name": "Qwen3_0_6B_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.qwen3_0_6b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_0_6B_SglangRecipe",
    },
    {
        "class_name": "Qwen3_0_6B_VllmRecipe",
        "module": "modal_training_gym.deploy_recipes.vllm_recipe.qwen3_0_6b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_0_6B_VllmRecipe",
    },
    {
        "class_name": "Qwen3_1_7B_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.qwen3_1_7b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_1_7B_SglangRecipe",
    },
    {
        "class_name": "Qwen3_1_7B_VllmRecipe",
        "module": "modal_training_gym.deploy_recipes.vllm_recipe.qwen3_1_7b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_1_7B_VllmRecipe",
    },
    {
        "class_name": "Qwen3_4B_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.qwen3_4b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_4B_SglangRecipe",
    },
    {
        "class_name": "Qwen3_4B_VllmRecipe",
        "module": "modal_training_gym.deploy_recipes.vllm_recipe.qwen3_4b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_4B_VllmRecipe",
    },
    {
        "class_name": "Qwen3_8B_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.qwen3_8b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_8B_SglangRecipe",
    },
    {
        "class_name": "Qwen3_8B_VllmRecipe",
        "module": "modal_training_gym.deploy_recipes.vllm_recipe.qwen3_8b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_8B_VllmRecipe",
    },
    {
        "class_name": "Qwen3_30B_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.qwen3_30b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_30B_SglangRecipe",
    },
    {
        "class_name": "Qwen3_30B_VllmRecipe",
        "module": "modal_training_gym.deploy_recipes.vllm_recipe.qwen3_30b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_30B_VllmRecipe",
    },
    {
        "class_name": "Qwen3_6_35B_SglangRecipe",
        "module": "modal_training_gym.deploy_recipes.sglang_recipe.qwen3_6_35b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_6_35B_SglangRecipe",
    },
    {
        "class_name": "Qwen3_6_35B_VllmRecipe",
        "module": "modal_training_gym.deploy_recipes.vllm_recipe.qwen3_6_35b",
        "group": "deployment",
        "class_type": "config_data",
        "sidebar_label": "Qwen3_6_35B_VllmRecipe",
    },
]

GROUPS = {
    "models": {"label": "Models", "order": 1},
    "datasets": {"label": "Datasets", "order": 2},
    "recipes": {"label": "Recipes", "order": 3},
    "training": {"label": "Training", "order": 4},
    "deployment": {"label": "Deployment", "order": 5},
}

SDK_SIDEBAR_CLASSES = frozenset(
    {
        "ModelConfig",
        "HFModelConfiguration",
        "ModelArchitecture",
        "ToolCall",
        "DatasetConfig",
        "HuggingFaceDataset",
        "HarborDataset",
        "TrainConfig",
        "TrainingRun",
        "TrainingGroup",
        "TrainResult",
        "MetricConfig",
        "TrackioConfig",
        "WandbConfig",
        "ModalRayCluster",
        "SlimeRecipe",
        "MilesRecipe",
        "CustomDeployment",
        "Endpoint",
        "ParsedResponse",
        "SglangRecipe",
        "VllmRecipe",
    }
)


CLASS_REFERENCE_PATHS = {
    entry["class_name"]: f"/reference/{entry['class_name'].lower()}/"
    for entry in API_REFERENCE_MANIFEST
}
