from __future__ import annotations

import argparse
import importlib
import inspect
import re
from collections import defaultdict
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from modal_training_gym.common import models
from modal_training_gym.common.models.base import ModelConfig

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_README = ROOT / "README.md"
BEGIN_MARKER = "<!-- BEGIN MODELS LIST -->"
END_MARKER = "<!-- END MODELS LIST -->"
BANNER = (
    "<!-- Auto-generated by scripts/generate_models_table.py from the recipe "
    "registries in modal_training_gym/train_recipes/*/__init__.py. -->"
)
FRAMEWORKS = (
    "modal_training_gym.train_recipes.slime_recipe",
    "modal_training_gym.train_recipes.miles_recipe",
)
DEPLOY_FRAMEWORKS = (
    "modal_training_gym.deploy_recipes.sglang_recipe",
    "modal_training_gym.deploy_recipes.vllm_recipe",
)
BASE_RECIPES = {"SlimeRecipe", "MilesRecipe"}
BASE_DEPLOY_RECIPES = {"SglangRecipe", "VllmRecipe"}
FRAMEWORK_BASES = frozenset({*BASE_RECIPES, *BASE_DEPLOY_RECIPES, "MilesConfig"})
MODEL_CONFIGS = {name.lower(): getattr(models, name) for name in models.__all__}
FAMILY_RE = re.compile(r"^([A-Za-z]+(?:\d+(?:\.\d+)*|\d+)?)")
HF_URL = "https://huggingface.co"
MODALITY_ORDER = {"image": 0, "audio": 1}


@dataclass(frozen=True)
class ModelLink:
    display_name: str
    href: str


@dataclass(frozen=True)
class ModelRow:
    family: str
    model: ModelLink
    modalities: tuple[str, ...]


def model_key(recipe_name: str) -> str:
    return recipe_name.split("_Recipe")[0].removesuffix("_LoRA").lower()


def family_of(hf_id: str) -> str:
    slug = hf_id.rsplit("/", 1)[-1]
    match = FAMILY_RE.match(slug)
    family = match.group(1) if match else slug
    return family.title() if family.islower() else family


def model_link(hf_id: str) -> ModelLink:
    display_name = hf_id.rsplit("/", 1)[-1]
    return ModelLink(display_name=display_name, href=f"{HF_URL}/{hf_id}")


def ordered_modalities(values: set[str]) -> tuple[str, ...]:
    return tuple(sorted(values, key=lambda name: (MODALITY_ORDER.get(name, 99), name)))


def recipe_trainable_modalities(recipe: Any) -> frozenset[str]:
    return frozenset(getattr(recipe, "trainable_modalities", None) or ())


def training_modalities(recipe: Any, config: Any) -> frozenset[str]:
    supported = getattr(config, "supported_modalities", None) or frozenset()
    return frozenset(supported) & recipe_trainable_modalities(recipe)


def render_modalities(modalities: tuple[str, ...]) -> str:
    if not modalities:
        return "—"
    return ", ".join(modalities)


def iter_registered_recipes() -> Iterator[tuple[str, Any, Any, str]]:
    for module_path in FRAMEWORKS:
        registry = importlib.import_module(module_path)
        for recipe_name in registry.__all__:
            if recipe_name in BASE_RECIPES:
                continue
            recipe = getattr(registry, recipe_name)
            config = recipe.model_config_class or MODEL_CONFIGS.get(
                model_key(recipe_name)
            )
            yield recipe_name, recipe, config, module_path


def _is_preset_class(obj: Any, name: str) -> bool:
    if name in FRAMEWORK_BASES or not inspect.isclass(obj):
        return False
    module = obj.__module__
    if issubclass(obj, ModelConfig):
        return "common.models" in module and not module.endswith(".base")
    return "train_recipes" in module


def collect_model_preset_names() -> frozenset[str]:
    names: set[str] = set()
    for recipe_name, _recipe, config, _module_path in iter_registered_recipes():
        names.add(recipe_name)
        if config is not None:
            names.add(config.__name__)
    for name in models.__all__:
        if _is_preset_class(getattr(models, name), name):
            names.add(name)
    return frozenset(names)


def collect_deploy_preset_names() -> frozenset[str]:
    names: set[str] = set()
    for module_path in DEPLOY_FRAMEWORKS:
        registry = importlib.import_module(module_path)
        for name in registry.__all__:
            if name not in BASE_DEPLOY_RECIPES:
                names.add(name)
    return frozenset(names)


def collect_models() -> tuple[ModelRow, ...]:
    by_hf_id: dict[str, set[str]] = defaultdict(set)
    unmatched: list[str] = []
    for recipe_name, recipe, config, module_path in iter_registered_recipes():
        model_name = getattr(config, "model_name", None)
        if not model_name:
            unmatched.append(f"{module_path}.{recipe_name}")
            continue
        by_hf_id[model_name].update(training_modalities(recipe, config))
    if unmatched:
        raise SystemExit(
            "No ModelConfig found for these recipes:\n  "
            + "\n  ".join(unmatched)
            + "\nSet model_config_class on the recipe, or export a matching "
            "ModelConfig from modal_training_gym.common.models."
        )
    return tuple(
        ModelRow(
            family=family_of(hf_id),
            model=model_link(hf_id),
            modalities=ordered_modalities(modalities),
        )
        for hf_id, modalities in sorted(
            by_hf_id.items(),
            key=lambda item: (family_of(item[0]), item[0].rsplit("/", 1)[-1]),
        )
    )


def render_section(models: tuple[ModelRow, ...]) -> str:
    rows = [
        f"| {row.family} | [{row.model.display_name}]({row.model.href}) | "
        f"{render_modalities(row.modalities)} |"
        for row in models
    ]
    return "\n".join(
        [
            BEGIN_MARKER,
            BANNER,
            "",
            "| Family | Model | Multimodal |",
            "|---|---|---|",
            *rows,
            END_MARKER,
        ]
    )


def rendered_readme(readme_path: Path, models: tuple[ModelRow, ...]) -> tuple[str, str]:
    content = readme_path.read_text()
    if BEGIN_MARKER not in content or END_MARKER not in content:
        raise SystemExit(
            f"Markers {BEGIN_MARKER} / {END_MARKER} not found in {readme_path}"
        )
    before, rest = content.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return content, f"{before}{render_section(models)}{after}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Family | Model | Multimodal table in README.md."
    )
    parser.add_argument("--readme", type=Path, default=DEFAULT_README)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the model table is out of date.",
    )
    args = parser.parse_args()
    models = collect_models()
    current, updated = rendered_readme(args.readme, models)
    count = len(models)
    if args.check:
        if current != updated:
            raise SystemExit(
                f"{args.readme} model table is out of date. Run "
                "uv run scripts/generate_models_table.py"
            )
        print(f"Model table is up to date ({count} models)")
        return
    if current != updated:
        args.readme.write_text(updated)
    print(f"Wrote model table ({count} models)")


if __name__ == "__main__":
    main()
