"""Generate the Models table in README.md from the train recipe registries.

Each recipe is matched to its `ModelConfig` by class name to recover the
canonical HuggingFace model name, which the class name alone does not encode
(`Qwen3_5_0_8b_Recipe` -> `Qwen3_5_0_8B.model_name` -> `Qwen/Qwen3.5-0.8B`).
Adding a recipe to a registry is therefore the only step needed to list a model.

uv run scripts/generate_models_table.py            # rewrite README.md
uv run scripts/generate_models_table.py --check    # fail if the table is stale
"""

from __future__ import annotations

import argparse
import importlib
from dataclasses import dataclass, field
from pathlib import Path

from modal_training_gym.common import models

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_README = ROOT / "README.md"

BEGIN_MARKER = "<!-- BEGIN MODELS TABLE -->"
END_MARKER = "<!-- END MODELS TABLE -->"
BANNER = (
    "<!-- Auto-generated by scripts/generate_models_table.py from the recipe "
    "registries in modal_training_gym/train_recipes/*/__init__.py. Do not edit "
    "by hand. -->"
)

# Framework label → recipe package, in the order frameworks appear in a row.
FRAMEWORKS: dict[str, str] = {
    "slime": "modal_training_gym.train_recipes.slime_recipe",
    "miles": "modal_training_gym.train_recipes.miles_recipe",
}

# Base recipe classes each registry exports alongside its model recipes.
BASE_RECIPES = {"SlimeRecipe", "MilesRecipe"}

# Model configs keyed by lowercased class name, for recipe name lookup.
MODEL_CONFIGS = {name.lower(): getattr(models, name) for name in models.__all__}


def _model_key(recipe_name: str) -> str:
    """`Kimi_K2_5_LoRA_Recipe` → `kimi_k2_5`, a ModelConfig class name.

    Everything from `_Recipe` onwards is dropped, as is a `_LoRA` qualifier —
    both describe how a model is trained rather than naming a different model.
    """
    return recipe_name.split("_Recipe")[0].removesuffix("_LoRA").lower()


@dataclass
class ModelRow:
    """One table row: a model and every recipe that trains it."""

    config_name: str
    frameworks: list[str] = field(default_factory=list)
    recipe_names: list[str] = field(default_factory=list)


def collect_models() -> dict[str, ModelRow]:
    """Map HuggingFace model name → the row describing its recipes."""
    table: dict[str, ModelRow] = {}
    unmatched: list[str] = []

    for framework, module_path in FRAMEWORKS.items():
        registry = importlib.import_module(module_path)
        for recipe_name in registry.__all__:
            if recipe_name in BASE_RECIPES:
                continue
            config = MODEL_CONFIGS.get(_model_key(recipe_name))
            model_name = getattr(config, "model_name", None)
            if not model_name:
                unmatched.append(f"{module_path}.{recipe_name}")
                continue
            row = table.setdefault(model_name, ModelRow(config.__name__))
            if framework not in row.frameworks:
                row.frameworks.append(framework)
            row.recipe_names.append(recipe_name)

    if unmatched:
        raise SystemExit(
            "No ModelConfig found for these recipes:\n  "
            + "\n  ".join(unmatched)
            + "\nExport a matching ModelConfig from modal_training_gym.common.models "
            "(class name = recipe name without the _Recipe suffix)."
        )
    return table


def _code_list(names: list[str]) -> str:
    return ", ".join(f"`{name}`" for name in names)


def render_section(table: dict[str, ModelRow]) -> str:
    rows = []
    for model_name in sorted(table):
        row = table[model_name]
        rows.append(
            f"| `{model_name}` | {_code_list(row.frameworks)} | "
            f"`{row.config_name}` | {_code_list(row.recipe_names)} |"
        )
    return "\n".join(
        [
            BEGIN_MARKER,
            BANNER,
            "",
            "| Model | Framework | ModelConfig | Recipe |",
            "|---|---|---|---|",
            *rows,
            END_MARKER,
        ]
    )


def rendered_readme(readme_path: Path, table: dict[str, ModelRow]) -> tuple[str, str]:
    """Return (current README content, content with a freshly rendered table)."""
    content = readme_path.read_text()
    if BEGIN_MARKER not in content or END_MARKER not in content:
        raise SystemExit(
            f"Markers {BEGIN_MARKER} / {END_MARKER} not found in {readme_path}"
        )
    before, rest = content.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return content, f"{before}{render_section(table)}{after}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Models table in README.md from the recipe registries."
    )
    parser.add_argument("--readme", type=Path, default=DEFAULT_README)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the table is out of date instead of rewriting it.",
    )
    args = parser.parse_args()

    table = collect_models()
    if not table:
        raise SystemExit("No recipes found in the recipe registries")

    current, updated = rendered_readme(args.readme, table)
    if args.check:
        if current != updated:
            raise SystemExit(
                f"{args.readme} Models table is out of date. Run: "
                "uv run scripts/generate_models_table.py"
            )
        print(f"Models table is up to date ({len(table)} models)")
        return

    if current != updated:
        args.readme.write_text(updated)
    print(f"Wrote Models table ({len(table)} models)")


if __name__ == "__main__":
    main()
