"""Deploy the autogenerated docs site on Modal.

Deploy with:

    uv run modal deploy docs/docs_app.py

Per Modal's web endpoint docs, custom domains are attached on the endpoint via
`custom_domains=[...]`, and the domain must already be registered and validated
in the workspace settings Domains tab before deploy succeeds.
"""

from __future__ import annotations

import os
import subprocess

import modal

APP_NAME = "training-gym-docs"
BUILD_ROOT = "/root/project"
SITE_DIR = f"{BUILD_ROOT}/site"
DOCS_ROOT = f"{BUILD_ROOT}/docs"
PORT = 8000


def _current_ref() -> str:
    if ref := os.getenv("GITHUB_REF_NAME"):
        return ref

    result = subprocess.run(
        ["git", "branch", "--show-current"],
        check=False,
        capture_output=True,
        text=True,
    )
    branch = result.stdout.strip()
    return branch or "main"


DOCS_REF = _current_ref()

image = (
    modal.Image.debian_slim(python_version="3.12")
    .uv_sync(groups=["docs"])
    .env({"GITHUB_REF_NAME": DOCS_REF})
    .add_local_file("README.md", f"{BUILD_ROOT}/README.md", copy=True)
    .add_local_file("tutorials/README.md", f"{BUILD_ROOT}/tutorials/README.md", copy=True)
    .add_local_dir("docs", f"{BUILD_ROOT}/docs", copy=True)
    .add_local_dir("scripts", f"{BUILD_ROOT}/scripts", copy=True)
    .workdir(DOCS_ROOT)
    .run_commands("python -m properdocs build -f mkdocs.yml --strict")
)

app = modal.App(APP_NAME, image=image)


@app.function(scaledown_window=300)
@modal.web_server(
    PORT,
    label="training-gym",
    custom_domains=["training-gym.modal.dev"],
)
def serve_docs():
    import subprocess

    subprocess.Popen(
        [
            "python",
            "-m",
            "http.server",
            str(PORT),
            "--bind",
            "0.0.0.0",
            "--directory",
            SITE_DIR,
        ]
    )
